// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: games.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGameToCollection = `-- name: AddGameToCollection :one
INSERT INTO user_games (user_id, game_id, status, played)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, game_id) DO UPDATE
SET status = EXCLUDED.status,
    played = user_games.played OR EXCLUDED.played
RETURNING user_id, game_id, status, user_rating, added_at, played
`

type AddGameToCollectionParams struct {
	UserID pgtype.UUID `json:"user_id"`
	GameID pgtype.UUID `json:"game_id"`
	Status GameStatus  `json:"status"`
	Played bool        `json:"played"`
}

func (q *Queries) AddGameToCollection(ctx context.Context, arg AddGameToCollectionParams) (UserGame, error) {
	row := q.db.QueryRow(ctx, addGameToCollection,
		arg.UserID,
		arg.GameID,
		arg.Status,
		arg.Played,
	)
	var i UserGame
	err := row.Scan(
		&i.UserID,
		&i.GameID,
		&i.Status,
		&i.UserRating,
		&i.AddedAt,
		&i.Played,
	)
	return i, err
}

const addToCollectionIfAbsent = `-- name: AddToCollectionIfAbsent :exec
INSERT INTO user_games (user_id, game_id, status, played)
VALUES ($1, $2, 'played', TRUE)
ON CONFLICT (user_id, game_id) DO UPDATE
SET played = TRUE
`

type AddToCollectionIfAbsentParams struct {
	UserID pgtype.UUID `json:"user_id"`
	GameID pgtype.UUID `json:"game_id"`
}

func (q *Queries) AddToCollectionIfAbsent(ctx context.Context, arg AddToCollectionIfAbsentParams) error {
	_, err := q.db.Exec(ctx, addToCollectionIfAbsent, arg.UserID, arg.GameID)
	return err
}

const getGameByBGGID = `-- name: GetGameByBGGID :one
SELECT id, bgg_id, title, min_players, max_players, playtime_mins, weight, image_url, categories, bgg_rating, cached_at, description FROM games WHERE bgg_id = $1
`

func (q *Queries) GetGameByBGGID(ctx context.Context, bggID int32) (Game, error) {
	row := q.db.QueryRow(ctx, getGameByBGGID, bggID)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.BggID,
		&i.Title,
		&i.MinPlayers,
		&i.MaxPlayers,
		&i.PlaytimeMins,
		&i.Weight,
		&i.ImageUrl,
		&i.Categories,
		&i.BggRating,
		&i.CachedAt,
		&i.Description,
	)
	return i, err
}

const getGameByID = `-- name: GetGameByID :one
SELECT id, bgg_id, title, min_players, max_players, playtime_mins, weight, image_url, categories, bgg_rating, cached_at, description FROM games WHERE id = $1
`

func (q *Queries) GetGameByID(ctx context.Context, id pgtype.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, getGameByID, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.BggID,
		&i.Title,
		&i.MinPlayers,
		&i.MaxPlayers,
		&i.PlaytimeMins,
		&i.Weight,
		&i.ImageUrl,
		&i.Categories,
		&i.BggRating,
		&i.CachedAt,
		&i.Description,
	)
	return i, err
}

const getGroupCollection = `-- name: GetGroupCollection :many
SELECT DISTINCT
    g.id, g.bgg_id, g.title, g.min_players, g.max_players, g.playtime_mins, g.weight, g.image_url, g.categories, g.bgg_rating, g.cached_at, g.description,
    ug.status
FROM games g
JOIN user_games ug ON g.id = ug.game_id
JOIN group_members gm ON ug.user_id = gm.user_id
WHERE gm.group_id = $1
  AND ug.status = 'owned'
ORDER BY g.title
`

type GetGroupCollectionRow struct {
	ID           pgtype.UUID        `json:"id"`
	BggID        int32              `json:"bgg_id"`
	Title        string             `json:"title"`
	MinPlayers   int32              `json:"min_players"`
	MaxPlayers   int32              `json:"max_players"`
	PlaytimeMins pgtype.Int4        `json:"playtime_mins"`
	Weight       pgtype.Numeric     `json:"weight"`
	ImageUrl     pgtype.Text        `json:"image_url"`
	Categories   []string           `json:"categories"`
	BggRating    pgtype.Numeric     `json:"bgg_rating"`
	CachedAt     pgtype.Timestamptz `json:"cached_at"`
	Description  pgtype.Text        `json:"description"`
	Status       GameStatus         `json:"status"`
}

func (q *Queries) GetGroupCollection(ctx context.Context, groupID pgtype.UUID) ([]GetGroupCollectionRow, error) {
	rows, err := q.db.Query(ctx, getGroupCollection, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGroupCollectionRow{}
	for rows.Next() {
		var i GetGroupCollectionRow
		if err := rows.Scan(
			&i.ID,
			&i.BggID,
			&i.Title,
			&i.MinPlayers,
			&i.MaxPlayers,
			&i.PlaytimeMins,
			&i.Weight,
			&i.ImageUrl,
			&i.Categories,
			&i.BggRating,
			&i.CachedAt,
			&i.Description,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserCollection = `-- name: GetUserCollection :many
SELECT
    g.id, g.bgg_id, g.title, g.min_players, g.max_players, g.playtime_mins, g.weight, g.image_url, g.categories, g.bgg_rating, g.cached_at, g.description,
    ug.status,
    ug.played,
    ug.user_rating,
    ug.added_at
FROM games g
JOIN user_games ug ON g.id = ug.game_id
WHERE ug.user_id = $1
ORDER BY ug.added_at DESC
`

type GetUserCollectionRow struct {
	ID           pgtype.UUID        `json:"id"`
	BggID        int32              `json:"bgg_id"`
	Title        string             `json:"title"`
	MinPlayers   int32              `json:"min_players"`
	MaxPlayers   int32              `json:"max_players"`
	PlaytimeMins pgtype.Int4        `json:"playtime_mins"`
	Weight       pgtype.Numeric     `json:"weight"`
	ImageUrl     pgtype.Text        `json:"image_url"`
	Categories   []string           `json:"categories"`
	BggRating    pgtype.Numeric     `json:"bgg_rating"`
	CachedAt     pgtype.Timestamptz `json:"cached_at"`
	Description  pgtype.Text        `json:"description"`
	Status       GameStatus         `json:"status"`
	Played       bool               `json:"played"`
	UserRating   pgtype.Int4        `json:"user_rating"`
	AddedAt      pgtype.Timestamptz `json:"added_at"`
}

func (q *Queries) GetUserCollection(ctx context.Context, userID pgtype.UUID) ([]GetUserCollectionRow, error) {
	rows, err := q.db.Query(ctx, getUserCollection, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserCollectionRow{}
	for rows.Next() {
		var i GetUserCollectionRow
		if err := rows.Scan(
			&i.ID,
			&i.BggID,
			&i.Title,
			&i.MinPlayers,
			&i.MaxPlayers,
			&i.PlaytimeMins,
			&i.Weight,
			&i.ImageUrl,
			&i.Categories,
			&i.BggRating,
			&i.CachedAt,
			&i.Description,
			&i.Status,
			&i.Played,
			&i.UserRating,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSessionsForGame = `-- name: GetUserSessionsForGame :many
SELECT
    s.id,
    s.group_id,
    s.game_id,
    s.played_at,
    s.duration_mins,
    s.notes,
    s.logged_by,
    g.title     AS game_title,
    g.image_url AS game_image
FROM sessions s
JOIN games g ON s.game_id = g.id
WHERE g.bgg_id = $1
  AND (s.logged_by = $2
       OR EXISTS (SELECT 1 FROM session_players sp WHERE sp.session_id = s.id AND sp.user_id = $2)
       OR (s.group_id IS NOT NULL AND EXISTS (
           SELECT 1 FROM group_members gm WHERE gm.group_id = s.group_id AND gm.user_id = $2
       )))
ORDER BY s.played_at DESC
`

type GetUserSessionsForGameParams struct {
	BggID  int32       `json:"bgg_id"`
	UserID pgtype.UUID `json:"user_id"`
}

type GetUserSessionsForGameRow struct {
	ID           pgtype.UUID        `json:"id"`
	GroupID      pgtype.UUID        `json:"group_id"`
	GameID       pgtype.UUID        `json:"game_id"`
	PlayedAt     pgtype.Timestamptz `json:"played_at"`
	DurationMins pgtype.Int4        `json:"duration_mins"`
	Notes        pgtype.Text        `json:"notes"`
	LoggedBy     pgtype.UUID        `json:"logged_by"`
	GameTitle    string             `json:"game_title"`
	GameImage    pgtype.Text        `json:"game_image"`
}

func (q *Queries) GetUserSessionsForGame(ctx context.Context, arg GetUserSessionsForGameParams) ([]GetUserSessionsForGameRow, error) {
	rows, err := q.db.Query(ctx, getUserSessionsForGame, arg.BggID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserSessionsForGameRow{}
	for rows.Next() {
		var i GetUserSessionsForGameRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.GameID,
			&i.PlayedAt,
			&i.DurationMins,
			&i.Notes,
			&i.LoggedBy,
			&i.GameTitle,
			&i.GameImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllGames = `-- name: ListAllGames :many
SELECT id, bgg_id, title, min_players, max_players, playtime_mins, weight, image_url, categories, bgg_rating, cached_at, description FROM games ORDER BY cached_at ASC
`

func (q *Queries) ListAllGames(ctx context.Context) ([]Game, error) {
	rows, err := q.db.Query(ctx, listAllGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Game{}
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.BggID,
			&i.Title,
			&i.MinPlayers,
			&i.MaxPlayers,
			&i.PlaytimeMins,
			&i.Weight,
			&i.ImageUrl,
			&i.Categories,
			&i.BggRating,
			&i.CachedAt,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFromCollection = `-- name: RemoveFromCollection :exec
DELETE FROM user_games WHERE user_id = $1 AND game_id = $2
`

type RemoveFromCollectionParams struct {
	UserID pgtype.UUID `json:"user_id"`
	GameID pgtype.UUID `json:"game_id"`
}

func (q *Queries) RemoveFromCollection(ctx context.Context, arg RemoveFromCollectionParams) error {
	_, err := q.db.Exec(ctx, removeFromCollection, arg.UserID, arg.GameID)
	return err
}

const searchLocalGames = `-- name: SearchLocalGames :many
SELECT id, bgg_id, title, min_players, max_players, playtime_mins, weight, image_url, categories, bgg_rating, cached_at, description FROM games WHERE title ILIKE '%' || $1 || '%' ORDER BY title LIMIT 10
`

func (q *Queries) SearchLocalGames(ctx context.Context, dollar_1 pgtype.Text) ([]Game, error) {
	rows, err := q.db.Query(ctx, searchLocalGames, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Game{}
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.BggID,
			&i.Title,
			&i.MinPlayers,
			&i.MaxPlayers,
			&i.PlaytimeMins,
			&i.Weight,
			&i.ImageUrl,
			&i.Categories,
			&i.BggRating,
			&i.CachedAt,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCollectionEntry = `-- name: UpdateCollectionEntry :one
UPDATE user_games
SET
    status      = COALESCE($3, status),
    user_rating = COALESCE($4, user_rating)
WHERE user_id = $1 AND game_id = $2
RETURNING user_id, game_id, status, user_rating, added_at, played
`

type UpdateCollectionEntryParams struct {
	UserID     pgtype.UUID    `json:"user_id"`
	GameID     pgtype.UUID    `json:"game_id"`
	Status     NullGameStatus `json:"status"`
	UserRating pgtype.Int4    `json:"user_rating"`
}

func (q *Queries) UpdateCollectionEntry(ctx context.Context, arg UpdateCollectionEntryParams) (UserGame, error) {
	row := q.db.QueryRow(ctx, updateCollectionEntry,
		arg.UserID,
		arg.GameID,
		arg.Status,
		arg.UserRating,
	)
	var i UserGame
	err := row.Scan(
		&i.UserID,
		&i.GameID,
		&i.Status,
		&i.UserRating,
		&i.AddedAt,
		&i.Played,
	)
	return i, err
}

const upsertGame = `-- name: UpsertGame :one

INSERT INTO games (bgg_id, title, min_players, max_players, playtime_mins, weight, image_url, categories, bgg_rating, description)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (bgg_id) DO UPDATE SET
    title         = EXCLUDED.title,
    min_players   = EXCLUDED.min_players,
    max_players   = EXCLUDED.max_players,
    playtime_mins = EXCLUDED.playtime_mins,
    weight        = EXCLUDED.weight,
    image_url     = EXCLUDED.image_url,
    categories    = EXCLUDED.categories,
    bgg_rating    = EXCLUDED.bgg_rating,
    description   = EXCLUDED.description,
    cached_at     = NOW()
RETURNING id, bgg_id, title, min_players, max_players, playtime_mins, weight, image_url, categories, bgg_rating, cached_at, description
`

type UpsertGameParams struct {
	BggID        int32          `json:"bgg_id"`
	Title        string         `json:"title"`
	MinPlayers   int32          `json:"min_players"`
	MaxPlayers   int32          `json:"max_players"`
	PlaytimeMins pgtype.Int4    `json:"playtime_mins"`
	Weight       pgtype.Numeric `json:"weight"`
	ImageUrl     pgtype.Text    `json:"image_url"`
	Categories   []string       `json:"categories"`
	BggRating    pgtype.Numeric `json:"bgg_rating"`
	Description  pgtype.Text    `json:"description"`
}

// db/queries/games.sql
func (q *Queries) UpsertGame(ctx context.Context, arg UpsertGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, upsertGame,
		arg.BggID,
		arg.Title,
		arg.MinPlayers,
		arg.MaxPlayers,
		arg.PlaytimeMins,
		arg.Weight,
		arg.ImageUrl,
		arg.Categories,
		arg.BggRating,
		arg.Description,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.BggID,
		&i.Title,
		&i.MinPlayers,
		&i.MaxPlayers,
		&i.PlaytimeMins,
		&i.Weight,
		&i.ImageUrl,
		&i.Categories,
		&i.BggRating,
		&i.CachedAt,
		&i.Description,
	)
	return i, err
}
