// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGroupMember = `-- name: AddGroupMember :one
INSERT INTO group_members (group_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (group_id, user_id) DO NOTHING
RETURNING group_id, user_id, role, joined_at
`

type AddGroupMemberParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
	Role    MemberRole  `json:"role"`
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, addGroupMember, arg.GroupID, arg.UserID, arg.Role)
	var i GroupMember
	err := row.Scan(
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const addSessionPlayer = `-- name: AddSessionPlayer :one
INSERT INTO session_players (session_id, user_id, result, score)
VALUES ($1, $2, $3, $4)
RETURNING session_id, user_id, result, score
`

type AddSessionPlayerParams struct {
	SessionID pgtype.UUID   `json:"session_id"`
	UserID    pgtype.UUID   `json:"user_id"`
	Result    SessionResult `json:"result"`
	Score     pgtype.Int4   `json:"score"`
}

func (q *Queries) AddSessionPlayer(ctx context.Context, arg AddSessionPlayerParams) (SessionPlayer, error) {
	row := q.db.QueryRow(ctx, addSessionPlayer,
		arg.SessionID,
		arg.UserID,
		arg.Result,
		arg.Score,
	)
	var i SessionPlayer
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.Result,
		&i.Score,
	)
	return i, err
}

const createGroup = `-- name: CreateGroup :one

INSERT INTO groups (name, created_by)
VALUES ($1, $2)
RETURNING id, name, invite_code, created_by, created_at
`

type CreateGroupParams struct {
	Name      string      `json:"name"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

// db/queries/groups.sql
func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.Name, arg.CreatedBy)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InviteCode,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (group_id, game_id, played_at, duration_mins, notes, logged_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, group_id, game_id, played_at, duration_mins, notes, logged_by
`

type CreateSessionParams struct {
	GroupID      pgtype.UUID        `json:"group_id"`
	GameID       pgtype.UUID        `json:"game_id"`
	PlayedAt     pgtype.Timestamptz `json:"played_at"`
	DurationMins pgtype.Int4        `json:"duration_mins"`
	Notes        pgtype.Text        `json:"notes"`
	LoggedBy     pgtype.UUID        `json:"logged_by"`
}

// db/queries/sessions.sql
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.GroupID,
		arg.GameID,
		arg.PlayedAt,
		arg.DurationMins,
		arg.Notes,
		arg.LoggedBy,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.GameID,
		&i.PlayedAt,
		&i.DurationMins,
		&i.Notes,
		&i.LoggedBy,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1 AND logged_by = $2
`

type DeleteSessionParams struct {
	ID       pgtype.UUID `json:"id"`
	LoggedBy pgtype.UUID `json:"logged_by"`
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) error {
	_, err := q.db.Exec(ctx, deleteSession, arg.ID, arg.LoggedBy)
	return err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, invite_code, created_by, created_at FROM groups WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id pgtype.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InviteCode,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupByInviteCode = `-- name: GetGroupByInviteCode :one
SELECT id, name, invite_code, created_by, created_at FROM groups WHERE invite_code = $1
`

func (q *Queries) GetGroupByInviteCode(ctx context.Context, inviteCode string) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByInviteCode, inviteCode)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InviteCode,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupMembers = `-- name: GetGroupMembers :many
SELECT
    u.id,
    u.display_name,
    u.avatar_url,
    gm.role,
    gm.joined_at
FROM users u
JOIN group_members gm ON u.id = gm.user_id
WHERE gm.group_id = $1
ORDER BY gm.joined_at ASC
`

type GetGroupMembersRow struct {
	ID          pgtype.UUID        `json:"id"`
	DisplayName string             `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	Role        MemberRole         `json:"role"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) GetGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]GetGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, getGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGroupMembersRow{}
	for rows.Next() {
		var i GetGroupMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupSessions = `-- name: GetGroupSessions :many
SELECT
    s.id, s.group_id, s.game_id, s.played_at, s.duration_mins, s.notes, s.logged_by,
    g.title AS game_title,
    g.image_url AS game_image
FROM sessions s
JOIN games g ON s.game_id = g.id
WHERE s.group_id = $1
ORDER BY s.played_at DESC
LIMIT $2 OFFSET $3
`

type GetGroupSessionsParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type GetGroupSessionsRow struct {
	ID           pgtype.UUID        `json:"id"`
	GroupID      pgtype.UUID        `json:"group_id"`
	GameID       pgtype.UUID        `json:"game_id"`
	PlayedAt     pgtype.Timestamptz `json:"played_at"`
	DurationMins pgtype.Int4        `json:"duration_mins"`
	Notes        pgtype.Text        `json:"notes"`
	LoggedBy     pgtype.UUID        `json:"logged_by"`
	GameTitle    string             `json:"game_title"`
	GameImage    pgtype.Text        `json:"game_image"`
}

func (q *Queries) GetGroupSessions(ctx context.Context, arg GetGroupSessionsParams) ([]GetGroupSessionsRow, error) {
	rows, err := q.db.Query(ctx, getGroupSessions, arg.GroupID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGroupSessionsRow{}
	for rows.Next() {
		var i GetGroupSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.GameID,
			&i.PlayedAt,
			&i.DurationMins,
			&i.Notes,
			&i.LoggedBy,
			&i.GameTitle,
			&i.GameImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionPlayers = `-- name: GetSessionPlayers :many
SELECT
    u.id,
    u.display_name,
    u.avatar_url,
    sp.result,
    sp.score
FROM users u
JOIN session_players sp ON u.id = sp.user_id
WHERE sp.session_id = $1
`

type GetSessionPlayersRow struct {
	ID          pgtype.UUID   `json:"id"`
	DisplayName string        `json:"display_name"`
	AvatarUrl   pgtype.Text   `json:"avatar_url"`
	Result      SessionResult `json:"result"`
	Score       pgtype.Int4   `json:"score"`
}

func (q *Queries) GetSessionPlayers(ctx context.Context, sessionID pgtype.UUID) ([]GetSessionPlayersRow, error) {
	rows, err := q.db.Query(ctx, getSessionPlayers, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSessionPlayersRow{}
	for rows.Next() {
		var i GetSessionPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Result,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserGroups = `-- name: GetUserGroups :many
SELECT g.id, g.name, g.invite_code, g.created_by, g.created_at
FROM groups g
JOIN group_members gm ON g.id = gm.group_id
WHERE gm.user_id = $1
ORDER BY g.created_at DESC
`

func (q *Queries) GetUserGroups(ctx context.Context, userID pgtype.UUID) ([]Group, error) {
	rows, err := q.db.Query(ctx, getUserGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.InviteCode,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSessions = `-- name: GetUserSessions :many
SELECT
    s.id,
    s.group_id,
    s.game_id,
    s.played_at,
    s.duration_mins,
    s.notes,
    s.logged_by,
    g.title  AS game_title,
    g.image_url AS game_image
FROM sessions s
JOIN games g ON s.game_id = g.id
WHERE s.logged_by = $1
   OR EXISTS (SELECT 1 FROM session_players sp WHERE sp.session_id = s.id AND sp.user_id = $1)
   OR (s.group_id IS NOT NULL AND EXISTS (
       SELECT 1 FROM group_members gm WHERE gm.group_id = s.group_id AND gm.user_id = $1
   ))
ORDER BY s.played_at DESC
LIMIT $2 OFFSET $3
`

type GetUserSessionsParams struct {
	LoggedBy pgtype.UUID `json:"logged_by"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type GetUserSessionsRow struct {
	ID           pgtype.UUID        `json:"id"`
	GroupID      pgtype.UUID        `json:"group_id"`
	GameID       pgtype.UUID        `json:"game_id"`
	PlayedAt     pgtype.Timestamptz `json:"played_at"`
	DurationMins pgtype.Int4        `json:"duration_mins"`
	Notes        pgtype.Text        `json:"notes"`
	LoggedBy     pgtype.UUID        `json:"logged_by"`
	GameTitle    string             `json:"game_title"`
	GameImage    pgtype.Text        `json:"game_image"`
}

func (q *Queries) GetUserSessions(ctx context.Context, arg GetUserSessionsParams) ([]GetUserSessionsRow, error) {
	rows, err := q.db.Query(ctx, getUserSessions, arg.LoggedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserSessionsRow{}
	for rows.Next() {
		var i GetUserSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.GameID,
			&i.PlayedAt,
			&i.DurationMins,
			&i.Notes,
			&i.LoggedBy,
			&i.GameTitle,
			&i.GameImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserStats = `-- name: GetUserStats :one
WITH my_sessions AS (
    SELECT s.id, s.game_id, s.played_at, s.duration_mins, g.title AS game_title
    FROM sessions s
    JOIN games g ON s.game_id = g.id
    WHERE s.logged_by = $1
       OR EXISTS (SELECT 1 FROM session_players sp2 WHERE sp2.session_id = s.id AND sp2.user_id = $1)
       OR (s.group_id IS NOT NULL AND EXISTS (
           SELECT 1 FROM group_members gm WHERE gm.group_id = s.group_id AND gm.user_id = $1
       ))
)
SELECT
    COUNT(ms.id)::int                                                                                        AS total_sessions,
    (COUNT(ms.id) FILTER (WHERE DATE_TRUNC('month', ms.played_at) = DATE_TRUNC('month', NOW())))::int       AS sessions_this_month,
    COUNT(DISTINCT ms.game_id)::int                                                                          AS unique_games,
    COALESCE(SUM(ms.duration_mins), 0)::int                                                                 AS total_playtime_mins,
    COALESCE((SELECT ms2.game_title FROM my_sessions ms2 GROUP BY ms2.game_id, ms2.game_title ORDER BY COUNT(*) DESC LIMIT 1), '')         AS most_played_game,
    COALESCE((SELECT COUNT(*)::int FROM my_sessions ms2 GROUP BY ms2.game_id, ms2.game_title ORDER BY COUNT(*) DESC LIMIT 1), 0)         AS most_played_game_count,
    (SELECT g2.image_url FROM my_sessions ms2 JOIN games g2 ON g2.id = ms2.game_id GROUP BY ms2.game_id, ms2.game_title, g2.image_url ORDER BY COUNT(*) DESC LIMIT 1) AS most_played_game_image,
    COUNT(CASE WHEN sp.result = 'win'::session_result THEN 1 END)::int                                     AS wins,
    COUNT(sp.result)::int                                                                                    AS total_results
FROM my_sessions ms
LEFT JOIN session_players sp ON sp.session_id = ms.id AND sp.user_id = $1
`

type GetUserStatsRow struct {
	TotalSessions       int32       `json:"total_sessions"`
	SessionsThisMonth   int32       `json:"sessions_this_month"`
	UniqueGames         int32       `json:"unique_games"`
	TotalPlaytimeMins   int32       `json:"total_playtime_mins"`
	MostPlayedGame      interface{} `json:"most_played_game"`
	MostPlayedGameCount interface{} `json:"most_played_game_count"`
	MostPlayedGameImage pgtype.Text `json:"most_played_game_image"`
	Wins                int32       `json:"wins"`
	TotalResults        int32       `json:"total_results"`
}

func (q *Queries) GetUserStats(ctx context.Context, userID pgtype.UUID) (GetUserStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserStats, userID)
	var i GetUserStatsRow
	err := row.Scan(
		&i.TotalSessions,
		&i.SessionsThisMonth,
		&i.UniqueGames,
		&i.TotalPlaytimeMins,
		&i.MostPlayedGame,
		&i.MostPlayedGameCount,
		&i.MostPlayedGameImage,
		&i.Wins,
		&i.TotalResults,
	)
	return i, err
}

const isGroupMember = `-- name: IsGroupMember :one
SELECT EXISTS (
    SELECT 1 FROM group_members
    WHERE group_id = $1 AND user_id = $2
) AS is_member
`

type IsGroupMemberParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) IsGroupMember(ctx context.Context, arg IsGroupMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isGroupMember, arg.GroupID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const updateSession = `-- name: UpdateSession :exec
UPDATE sessions SET played_at = $2 WHERE id = $1 AND logged_by = $3
`

type UpdateSessionParams struct {
	ID       pgtype.UUID        `json:"id"`
	PlayedAt pgtype.Timestamptz `json:"played_at"`
	LoggedBy pgtype.UUID        `json:"logged_by"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.Exec(ctx, updateSession, arg.ID, arg.PlayedAt, arg.LoggedBy)
	return err
}

const updateSessionPlayer = `-- name: UpdateSessionPlayer :exec
UPDATE session_players
SET result = $3, score = $4
WHERE session_id = $1 AND user_id = $2
`

type UpdateSessionPlayerParams struct {
	SessionID pgtype.UUID   `json:"session_id"`
	UserID    pgtype.UUID   `json:"user_id"`
	Result    SessionResult `json:"result"`
	Score     pgtype.Int4   `json:"score"`
}

func (q *Queries) UpdateSessionPlayer(ctx context.Context, arg UpdateSessionPlayerParams) error {
	_, err := q.db.Exec(ctx, updateSessionPlayer,
		arg.SessionID,
		arg.UserID,
		arg.Result,
		arg.Score,
	)
	return err
}
