// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lists.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGameToList = `-- name: AddGameToList :exec
INSERT INTO list_games (list_id, game_id, position)
VALUES ($1, $2, $3)
ON CONFLICT (list_id, game_id) DO UPDATE SET position = EXCLUDED.position
`

type AddGameToListParams struct {
	ListID   pgtype.UUID `json:"list_id"`
	GameID   pgtype.UUID `json:"game_id"`
	Position int16       `json:"position"`
}

func (q *Queries) AddGameToList(ctx context.Context, arg AddGameToListParams) error {
	_, err := q.db.Exec(ctx, addGameToList, arg.ListID, arg.GameID, arg.Position)
	return err
}

const createList = `-- name: CreateList :one

INSERT INTO lists (user_id, title, description)
VALUES ($1, $2, $3)
RETURNING id, user_id, title, description, created_at, updated_at
`

type CreateListParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
}

// db/queries/lists.sql
func (q *Queries) CreateList(ctx context.Context, arg CreateListParams) (List, error) {
	row := q.db.QueryRow(ctx, createList, arg.UserID, arg.Title, arg.Description)
	var i List
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteList = `-- name: DeleteList :exec
DELETE FROM lists WHERE id = $1 AND user_id = $2
`

type DeleteListParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteList(ctx context.Context, arg DeleteListParams) error {
	_, err := q.db.Exec(ctx, deleteList, arg.ID, arg.UserID)
	return err
}

const getListByID = `-- name: GetListByID :one
SELECT l.id, l.user_id, l.title, l.description, l.created_at, l.updated_at, COUNT(lg.game_id)::int AS game_count
FROM lists l
LEFT JOIN list_games lg ON lg.list_id = l.id
WHERE l.id = $1
GROUP BY l.id
`

type GetListByIDRow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	GameCount   int32              `json:"game_count"`
}

func (q *Queries) GetListByID(ctx context.Context, id pgtype.UUID) (GetListByIDRow, error) {
	row := q.db.QueryRow(ctx, getListByID, id)
	var i GetListByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GameCount,
	)
	return i, err
}

const getListGameCount = `-- name: GetListGameCount :one
SELECT COUNT(*)::int AS count FROM list_games WHERE list_id = $1
`

func (q *Queries) GetListGameCount(ctx context.Context, listID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getListGameCount, listID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const getListGames = `-- name: GetListGames :many
SELECT
    g.id,
    g.bgg_id,
    g.title,
    g.image_url,
    g.bgg_rating,
    g.weight,
    g.min_players,
    g.max_players,
    g.playtime_mins,
    lg.position
FROM list_games lg
JOIN games g ON g.id = lg.game_id
WHERE lg.list_id = $1
ORDER BY lg.position
`

type GetListGamesRow struct {
	ID           pgtype.UUID    `json:"id"`
	BggID        int32          `json:"bgg_id"`
	Title        string         `json:"title"`
	ImageUrl     pgtype.Text    `json:"image_url"`
	BggRating    pgtype.Numeric `json:"bgg_rating"`
	Weight       pgtype.Numeric `json:"weight"`
	MinPlayers   int32          `json:"min_players"`
	MaxPlayers   int32          `json:"max_players"`
	PlaytimeMins pgtype.Int4    `json:"playtime_mins"`
	Position     int16          `json:"position"`
}

func (q *Queries) GetListGames(ctx context.Context, listID pgtype.UUID) ([]GetListGamesRow, error) {
	rows, err := q.db.Query(ctx, getListGames, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetListGamesRow{}
	for rows.Next() {
		var i GetListGamesRow
		if err := rows.Scan(
			&i.ID,
			&i.BggID,
			&i.Title,
			&i.ImageUrl,
			&i.BggRating,
			&i.Weight,
			&i.MinPlayers,
			&i.MaxPlayers,
			&i.PlaytimeMins,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListsByUser = `-- name: GetListsByUser :many
SELECT l.id, l.user_id, l.title, l.description, l.created_at, l.updated_at, COUNT(lg.game_id)::int AS game_count
FROM lists l
LEFT JOIN list_games lg ON lg.list_id = l.id
WHERE l.user_id = $1
GROUP BY l.id
ORDER BY l.created_at DESC
`

type GetListsByUserRow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	GameCount   int32              `json:"game_count"`
}

func (q *Queries) GetListsByUser(ctx context.Context, userID pgtype.UUID) ([]GetListsByUserRow, error) {
	rows, err := q.db.Query(ctx, getListsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetListsByUserRow{}
	for rows.Next() {
		var i GetListsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GameCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGameFromList = `-- name: RemoveGameFromList :exec
DELETE FROM list_games WHERE list_id = $1 AND game_id = $2
`

type RemoveGameFromListParams struct {
	ListID pgtype.UUID `json:"list_id"`
	GameID pgtype.UUID `json:"game_id"`
}

func (q *Queries) RemoveGameFromList(ctx context.Context, arg RemoveGameFromListParams) error {
	_, err := q.db.Exec(ctx, removeGameFromList, arg.ListID, arg.GameID)
	return err
}

const reorderListGames = `-- name: ReorderListGames :exec
UPDATE list_games SET position = $3
WHERE list_id = $1 AND game_id = $2
`

type ReorderListGamesParams struct {
	ListID   pgtype.UUID `json:"list_id"`
	GameID   pgtype.UUID `json:"game_id"`
	Position int16       `json:"position"`
}

func (q *Queries) ReorderListGames(ctx context.Context, arg ReorderListGamesParams) error {
	_, err := q.db.Exec(ctx, reorderListGames, arg.ListID, arg.GameID, arg.Position)
	return err
}

const updateList = `-- name: UpdateList :one
UPDATE lists
SET
    title       = COALESCE($3, title),
    description = COALESCE($4, description),
    updated_at  = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, description, created_at, updated_at
`

type UpdateListParams struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	Title       pgtype.Text `json:"title"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateList(ctx context.Context, arg UpdateListParams) (List, error) {
	row := q.db.QueryRow(ctx, updateList,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
	)
	var i List
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
