// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityType string

const (
	ActivityTypeSessionLogged ActivityType = "session_logged"
	ActivityTypeGameAdded     ActivityType = "game_added"
	ActivityTypeGameForTrade  ActivityType = "game_for_trade"
	ActivityTypeListCreated   ActivityType = "list_created"
	ActivityTypeGroupJoined   ActivityType = "group_joined"
)

func (e *ActivityType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActivityType(s)
	case string:
		*e = ActivityType(s)
	default:
		return fmt.Errorf("unsupported scan type for ActivityType: %T", src)
	}
	return nil
}

type NullActivityType struct {
	ActivityType ActivityType `json:"activity_type"`
	Valid        bool         `json:"valid"` // Valid is true if ActivityType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActivityType) Scan(value interface{}) error {
	if value == nil {
		ns.ActivityType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActivityType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActivityType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActivityType), nil
}

type GameStatus string

const (
	GameStatusOwned      GameStatus = "owned"
	GameStatusWantToPlay GameStatus = "want_to_play"
	GameStatusForTrade   GameStatus = "for_trade"
	GameStatusWishlist   GameStatus = "wishlist"
	GameStatusPlayed     GameStatus = "played"
)

func (e *GameStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GameStatus(s)
	case string:
		*e = GameStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for GameStatus: %T", src)
	}
	return nil
}

type NullGameStatus struct {
	GameStatus GameStatus `json:"game_status"`
	Valid      bool       `json:"valid"` // Valid is true if GameStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGameStatus) Scan(value interface{}) error {
	if value == nil {
		ns.GameStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GameStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGameStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GameStatus), nil
}

type MemberRole string

const (
	MemberRoleAdmin  MemberRole = "admin"
	MemberRoleMember MemberRole = "member"
)

func (e *MemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberRole(s)
	case string:
		*e = MemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberRole: %T", src)
	}
	return nil
}

type NullMemberRole struct {
	MemberRole MemberRole `json:"member_role"`
	Valid      bool       `json:"valid"` // Valid is true if MemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.MemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberRole), nil
}

type NightStatus string

const (
	NightStatusPolling   NightStatus = "polling"
	NightStatusConfirmed NightStatus = "confirmed"
	NightStatusCancelled NightStatus = "cancelled"
)

func (e *NightStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NightStatus(s)
	case string:
		*e = NightStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for NightStatus: %T", src)
	}
	return nil
}

type NullNightStatus struct {
	NightStatus NightStatus `json:"night_status"`
	Valid       bool        `json:"valid"` // Valid is true if NightStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNightStatus) Scan(value interface{}) error {
	if value == nil {
		ns.NightStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NightStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNightStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NightStatus), nil
}

type SessionResult string

const (
	SessionResultWin  SessionResult = "win"
	SessionResultLoss SessionResult = "loss"
	SessionResultDraw SessionResult = "draw"
	SessionResultDnf  SessionResult = "dnf"
)

func (e *SessionResult) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionResult(s)
	case string:
		*e = SessionResult(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionResult: %T", src)
	}
	return nil
}

type NullSessionResult struct {
	SessionResult SessionResult `json:"session_result"`
	Valid         bool          `json:"valid"` // Valid is true if SessionResult is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionResult) Scan(value interface{}) error {
	if value == nil {
		ns.SessionResult, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionResult.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionResult) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionResult), nil
}

type Activity struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Type      ActivityType       `json:"type"`
	GameID    pgtype.UUID        `json:"game_id"`
	SessionID pgtype.UUID        `json:"session_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ListID    pgtype.UUID        `json:"list_id"`
	GroupID   pgtype.UUID        `json:"group_id"`
}

type AvailabilityResponse struct {
	NightID   pgtype.UUID        `json:"night_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Date      pgtype.Timestamptz `json:"date"`
	Available bool               `json:"available"`
}

type Follow struct {
	FollowerID  pgtype.UUID        `json:"follower_id"`
	FollowingID pgtype.UUID        `json:"following_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Game struct {
	ID           pgtype.UUID        `json:"id"`
	BggID        int32              `json:"bgg_id"`
	Title        string             `json:"title"`
	MinPlayers   int32              `json:"min_players"`
	MaxPlayers   int32              `json:"max_players"`
	PlaytimeMins pgtype.Int4        `json:"playtime_mins"`
	Weight       pgtype.Numeric     `json:"weight"`
	ImageUrl     pgtype.Text        `json:"image_url"`
	Categories   []string           `json:"categories"`
	BggRating    pgtype.Numeric     `json:"bgg_rating"`
	CachedAt     pgtype.Timestamptz `json:"cached_at"`
	Description  pgtype.Text        `json:"description"`
}

type GameNight struct {
	ID            pgtype.UUID          `json:"id"`
	GroupID       pgtype.UUID          `json:"group_id"`
	ProposedDates []pgtype.Timestamptz `json:"proposed_dates"`
	ConfirmedDate pgtype.Timestamptz   `json:"confirmed_date"`
	Status        NightStatus          `json:"status"`
	CreatedBy     pgtype.UUID          `json:"created_by"`
	CreatedAt     pgtype.Timestamptz   `json:"created_at"`
}

type Group struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	InviteCode string             `json:"invite_code"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type GroupMember struct {
	GroupID  pgtype.UUID        `json:"group_id"`
	UserID   pgtype.UUID        `json:"user_id"`
	Role     MemberRole         `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type List struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ListGame struct {
	ListID   pgtype.UUID `json:"list_id"`
	GameID   pgtype.UUID `json:"game_id"`
	Position int16       `json:"position"`
}

type Review struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	GameID    pgtype.UUID        `json:"game_id"`
	Rating    float32            `json:"rating"`
	Body      pgtype.Text        `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RoundTable struct {
	UserID   pgtype.UUID `json:"user_id"`
	GameID   pgtype.UUID `json:"game_id"`
	Position int16       `json:"position"`
}

type Session struct {
	ID           pgtype.UUID        `json:"id"`
	GroupID      pgtype.UUID        `json:"group_id"`
	GameID       pgtype.UUID        `json:"game_id"`
	PlayedAt     pgtype.Timestamptz `json:"played_at"`
	DurationMins pgtype.Int4        `json:"duration_mins"`
	Notes        pgtype.Text        `json:"notes"`
	LoggedBy     pgtype.UUID        `json:"logged_by"`
}

type SessionPlayer struct {
	SessionID pgtype.UUID   `json:"session_id"`
	UserID    pgtype.UUID   `json:"user_id"`
	Result    SessionResult `json:"result"`
	Score     pgtype.Int4   `json:"score"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	Password    string             `json:"password"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	GoogleID    pgtype.Text        `json:"google_id"`
	Bio         pgtype.Text        `json:"bio"`
}

type UserGame struct {
	UserID     pgtype.UUID        `json:"user_id"`
	GameID     pgtype.UUID        `json:"game_id"`
	Status     GameStatus         `json:"status"`
	UserRating pgtype.Int4        `json:"user_rating"`
	AddedAt    pgtype.Timestamptz `json:"added_at"`
	Played     bool               `json:"played"`
}
