// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddGameToCollection(ctx context.Context, arg AddGameToCollectionParams) (UserGame, error)
	AddGameToList(ctx context.Context, arg AddGameToListParams) error
	AddGroupMember(ctx context.Context, arg AddGroupMemberParams) (GroupMember, error)
	AddSessionPlayer(ctx context.Context, arg AddSessionPlayerParams) (SessionPlayer, error)
	AddToCollectionIfAbsent(ctx context.Context, arg AddToCollectionIfAbsentParams) error
	ClearRoundTable(ctx context.Context, userID pgtype.UUID) error
	CreateGoogleUser(ctx context.Context, arg CreateGoogleUserParams) (User, error)
	// db/queries/groups.sql
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	// db/queries/lists.sql
	CreateList(ctx context.Context, arg CreateListParams) (List, error)
	// db/queries/sessions.sql
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// db/queries/users.sql
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteList(ctx context.Context, arg DeleteListParams) error
	DeleteReview(ctx context.Context, arg DeleteReviewParams) error
	DeleteSession(ctx context.Context, arg DeleteSessionParams) error
	// db/queries/social.sql
	FollowUser(ctx context.Context, arg FollowUserParams) error
	GetFeed(ctx context.Context, arg GetFeedParams) ([]GetFeedRow, error)
	GetFollowerCount(ctx context.Context, followingID pgtype.UUID) (int64, error)
	GetFollowers(ctx context.Context, followingID pgtype.UUID) ([]GetFollowersRow, error)
	GetFollowing(ctx context.Context, followerID pgtype.UUID) ([]GetFollowingRow, error)
	GetFollowingCount(ctx context.Context, followerID pgtype.UUID) (int64, error)
	GetGameByBGGID(ctx context.Context, bggID int32) (Game, error)
	GetGameByID(ctx context.Context, id pgtype.UUID) (Game, error)
	GetGameReviewStats(ctx context.Context, gameID pgtype.UUID) ([]GetGameReviewStatsRow, error)
	GetGroupByID(ctx context.Context, id pgtype.UUID) (Group, error)
	GetGroupByInviteCode(ctx context.Context, inviteCode string) (Group, error)
	GetGroupCollection(ctx context.Context, groupID pgtype.UUID) ([]GetGroupCollectionRow, error)
	GetGroupMates(ctx context.Context, userID pgtype.UUID) ([]GetGroupMatesRow, error)
	GetGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]GetGroupMembersRow, error)
	GetGroupSessions(ctx context.Context, arg GetGroupSessionsParams) ([]GetGroupSessionsRow, error)
	GetListByID(ctx context.Context, id pgtype.UUID) (GetListByIDRow, error)
	GetListGameCount(ctx context.Context, listID pgtype.UUID) (int32, error)
	GetListGames(ctx context.Context, listID pgtype.UUID) ([]GetListGamesRow, error)
	GetListsByUser(ctx context.Context, userID pgtype.UUID) ([]GetListsByUserRow, error)
	GetReviewableGames(ctx context.Context, userID pgtype.UUID) ([]GetReviewableGamesRow, error)
	// db/queries/round_table.sql
	GetRoundTable(ctx context.Context, userID pgtype.UUID) ([]GetRoundTableRow, error)
	GetSessionPlayers(ctx context.Context, sessionID pgtype.UUID) ([]GetSessionPlayersRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByGoogleID(ctx context.Context, googleID pgtype.Text) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserCollection(ctx context.Context, userID pgtype.UUID) ([]GetUserCollectionRow, error)
	GetUserGroups(ctx context.Context, userID pgtype.UUID) ([]Group, error)
	GetUserReview(ctx context.Context, arg GetUserReviewParams) (Review, error)
	GetUserReviews(ctx context.Context, userID pgtype.UUID) ([]GetUserReviewsRow, error)
	GetUserSessions(ctx context.Context, arg GetUserSessionsParams) ([]GetUserSessionsRow, error)
	GetUserSessionsForGame(ctx context.Context, arg GetUserSessionsForGameParams) ([]GetUserSessionsForGameRow, error)
	GetUserStats(ctx context.Context, userID pgtype.UUID) (GetUserStatsRow, error)
	InsertActivity(ctx context.Context, arg InsertActivityParams) error
	IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error)
	IsGroupMember(ctx context.Context, arg IsGroupMemberParams) (bool, error)
	LinkGoogleID(ctx context.Context, arg LinkGoogleIDParams) (User, error)
	ListAllGames(ctx context.Context) ([]Game, error)
	RemoveFromCollection(ctx context.Context, arg RemoveFromCollectionParams) error
	RemoveGameFromList(ctx context.Context, arg RemoveGameFromListParams) error
	ReorderListGames(ctx context.Context, arg ReorderListGamesParams) error
	SearchLocalGames(ctx context.Context, dollar_1 pgtype.Text) ([]Game, error)
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error)
	SetRoundTableSlot(ctx context.Context, arg SetRoundTableSlotParams) error
	UnfollowUser(ctx context.Context, arg UnfollowUserParams) error
	UpdateCollectionEntry(ctx context.Context, arg UpdateCollectionEntryParams) (UserGame, error)
	UpdateList(ctx context.Context, arg UpdateListParams) (List, error)
	UpdateSession(ctx context.Context, arg UpdateSessionParams) error
	UpdateSessionPlayer(ctx context.Context, arg UpdateSessionPlayerParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	// db/queries/games.sql
	UpsertGame(ctx context.Context, arg UpsertGameParams) (Game, error)
	// db/queries/reviews.sql
	UpsertReview(ctx context.Context, arg UpsertReviewParams) (Review, error)
}

var _ Querier = (*Queries)(nil)
