// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteReview = `-- name: DeleteReview :exec
DELETE FROM reviews WHERE user_id = $1 AND game_id = $2
`

type DeleteReviewParams struct {
	UserID pgtype.UUID `json:"user_id"`
	GameID pgtype.UUID `json:"game_id"`
}

func (q *Queries) DeleteReview(ctx context.Context, arg DeleteReviewParams) error {
	_, err := q.db.Exec(ctx, deleteReview, arg.UserID, arg.GameID)
	return err
}

const getGameReviewStats = `-- name: GetGameReviewStats :many
SELECT
    rating,
    COUNT(*)::int AS count
FROM reviews
WHERE game_id = $1
GROUP BY rating
ORDER BY rating DESC
`

type GetGameReviewStatsRow struct {
	Rating float32 `json:"rating"`
	Count  int32   `json:"count"`
}

func (q *Queries) GetGameReviewStats(ctx context.Context, gameID pgtype.UUID) ([]GetGameReviewStatsRow, error) {
	rows, err := q.db.Query(ctx, getGameReviewStats, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGameReviewStatsRow{}
	for rows.Next() {
		var i GetGameReviewStatsRow
		if err := rows.Scan(&i.Rating, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReviewableGames = `-- name: GetReviewableGames :many
SELECT DISTINCT g.id, g.bgg_id, g.title, g.image_url
FROM games g
JOIN user_games ug ON ug.game_id = g.id
WHERE ug.user_id = $1
  AND (ug.status = 'owned' OR ug.played = TRUE)
ORDER BY g.title
`

type GetReviewableGamesRow struct {
	ID       pgtype.UUID `json:"id"`
	BggID    int32       `json:"bgg_id"`
	Title    string      `json:"title"`
	ImageUrl pgtype.Text `json:"image_url"`
}

func (q *Queries) GetReviewableGames(ctx context.Context, userID pgtype.UUID) ([]GetReviewableGamesRow, error) {
	rows, err := q.db.Query(ctx, getReviewableGames, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReviewableGamesRow{}
	for rows.Next() {
		var i GetReviewableGamesRow
		if err := rows.Scan(
			&i.ID,
			&i.BggID,
			&i.Title,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserReview = `-- name: GetUserReview :one
SELECT id, user_id, game_id, rating, body, created_at, updated_at FROM reviews WHERE user_id = $1 AND game_id = $2
`

type GetUserReviewParams struct {
	UserID pgtype.UUID `json:"user_id"`
	GameID pgtype.UUID `json:"game_id"`
}

func (q *Queries) GetUserReview(ctx context.Context, arg GetUserReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, getUserReview, arg.UserID, arg.GameID)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GameID,
		&i.Rating,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserReviews = `-- name: GetUserReviews :many
SELECT
    r.id, r.user_id, r.game_id, r.rating, r.body, r.created_at, r.updated_at,
    g.title     AS game_title,
    g.image_url AS game_image,
    g.bgg_id    AS game_bgg_id
FROM reviews r
JOIN games g ON g.id = r.game_id
WHERE r.user_id = $1
ORDER BY r.updated_at DESC
`

type GetUserReviewsRow struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	GameID    pgtype.UUID        `json:"game_id"`
	Rating    float32            `json:"rating"`
	Body      pgtype.Text        `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	GameTitle string             `json:"game_title"`
	GameImage pgtype.Text        `json:"game_image"`
	GameBggID int32              `json:"game_bgg_id"`
}

func (q *Queries) GetUserReviews(ctx context.Context, userID pgtype.UUID) ([]GetUserReviewsRow, error) {
	rows, err := q.db.Query(ctx, getUserReviews, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserReviewsRow{}
	for rows.Next() {
		var i GetUserReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GameID,
			&i.Rating,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GameTitle,
			&i.GameImage,
			&i.GameBggID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertReview = `-- name: UpsertReview :one

INSERT INTO reviews (user_id, game_id, rating, body)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, game_id) DO UPDATE
SET rating     = EXCLUDED.rating,
    body       = EXCLUDED.body,
    updated_at = NOW()
RETURNING id, user_id, game_id, rating, body, created_at, updated_at
`

type UpsertReviewParams struct {
	UserID pgtype.UUID `json:"user_id"`
	GameID pgtype.UUID `json:"game_id"`
	Rating float32     `json:"rating"`
	Body   pgtype.Text `json:"body"`
}

// db/queries/reviews.sql
func (q *Queries) UpsertReview(ctx context.Context, arg UpsertReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, upsertReview,
		arg.UserID,
		arg.GameID,
		arg.Rating,
		arg.Body,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GameID,
		&i.Rating,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
