// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: round_table.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearRoundTable = `-- name: ClearRoundTable :exec
DELETE FROM round_table WHERE user_id = $1
`

func (q *Queries) ClearRoundTable(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearRoundTable, userID)
	return err
}

const getRoundTable = `-- name: GetRoundTable :many

SELECT
    g.id,
    g.bgg_id,
    g.title,
    g.min_players,
    g.max_players,
    g.playtime_mins,
    g.weight,
    g.image_url,
    g.categories,
    g.bgg_rating,
    g.cached_at,
    rt.position
FROM round_table rt
JOIN games g ON g.id = rt.game_id
WHERE rt.user_id = $1
ORDER BY rt.position
`

type GetRoundTableRow struct {
	ID           pgtype.UUID        `json:"id"`
	BggID        int32              `json:"bgg_id"`
	Title        string             `json:"title"`
	MinPlayers   int32              `json:"min_players"`
	MaxPlayers   int32              `json:"max_players"`
	PlaytimeMins pgtype.Int4        `json:"playtime_mins"`
	Weight       pgtype.Numeric     `json:"weight"`
	ImageUrl     pgtype.Text        `json:"image_url"`
	Categories   []string           `json:"categories"`
	BggRating    pgtype.Numeric     `json:"bgg_rating"`
	CachedAt     pgtype.Timestamptz `json:"cached_at"`
	Position     int16              `json:"position"`
}

// db/queries/round_table.sql
func (q *Queries) GetRoundTable(ctx context.Context, userID pgtype.UUID) ([]GetRoundTableRow, error) {
	rows, err := q.db.Query(ctx, getRoundTable, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRoundTableRow{}
	for rows.Next() {
		var i GetRoundTableRow
		if err := rows.Scan(
			&i.ID,
			&i.BggID,
			&i.Title,
			&i.MinPlayers,
			&i.MaxPlayers,
			&i.PlaytimeMins,
			&i.Weight,
			&i.ImageUrl,
			&i.Categories,
			&i.BggRating,
			&i.CachedAt,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRoundTableSlot = `-- name: SetRoundTableSlot :exec
INSERT INTO round_table (user_id, game_id, position)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, position) DO UPDATE SET game_id = EXCLUDED.game_id
`

type SetRoundTableSlotParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	GameID   pgtype.UUID `json:"game_id"`
	Position int16       `json:"position"`
}

func (q *Queries) SetRoundTableSlot(ctx context.Context, arg SetRoundTableSlotParams) error {
	_, err := q.db.Exec(ctx, setRoundTableSlot, arg.UserID, arg.GameID, arg.Position)
	return err
}
