// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: social.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const followUser = `-- name: FollowUser :exec

INSERT INTO follows (follower_id, following_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type FollowUserParams struct {
	FollowerID  pgtype.UUID `json:"follower_id"`
	FollowingID pgtype.UUID `json:"following_id"`
}

// db/queries/social.sql
func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) error {
	_, err := q.db.Exec(ctx, followUser, arg.FollowerID, arg.FollowingID)
	return err
}

const getFeed = `-- name: GetFeed :many
SELECT
    a.id            AS activity_id,
    a.type,
    a.created_at,
    u.id            AS actor_id,
    u.display_name,
    u.avatar_url,
    g.id            AS game_id,
    g.title         AS game_title,
    g.image_url     AS game_image,
    s.id            AS session_id,
    s.notes         AS session_notes,
    s.duration_mins AS session_duration,
    lst.id          AS list_id,
    lst.title       AS list_title,
    grp.id          AS group_id,
    grp.name        AS group_name
FROM activity a
JOIN users u ON u.id = a.user_id
LEFT JOIN games g ON g.id = a.game_id
LEFT JOIN sessions s ON s.id = a.session_id
LEFT JOIN lists lst ON lst.id = a.list_id
LEFT JOIN groups grp ON grp.id = a.group_id
WHERE a.user_id = $1
   OR a.user_id IN (
    SELECT following_id FROM follows WHERE follower_id = $1
)
ORDER BY a.created_at DESC
LIMIT $2 OFFSET $3
`

type GetFeedParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type GetFeedRow struct {
	ActivityID      pgtype.UUID        `json:"activity_id"`
	Type            ActivityType       `json:"type"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ActorID         pgtype.UUID        `json:"actor_id"`
	DisplayName     string             `json:"display_name"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	GameID          pgtype.UUID        `json:"game_id"`
	GameTitle       pgtype.Text        `json:"game_title"`
	GameImage       pgtype.Text        `json:"game_image"`
	SessionID       pgtype.UUID        `json:"session_id"`
	SessionNotes    pgtype.Text        `json:"session_notes"`
	SessionDuration pgtype.Int4        `json:"session_duration"`
	ListID          pgtype.UUID        `json:"list_id"`
	ListTitle       pgtype.Text        `json:"list_title"`
	GroupID         pgtype.UUID        `json:"group_id"`
	GroupName       pgtype.Text        `json:"group_name"`
}

func (q *Queries) GetFeed(ctx context.Context, arg GetFeedParams) ([]GetFeedRow, error) {
	rows, err := q.db.Query(ctx, getFeed, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFeedRow{}
	for rows.Next() {
		var i GetFeedRow
		if err := rows.Scan(
			&i.ActivityID,
			&i.Type,
			&i.CreatedAt,
			&i.ActorID,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.GameID,
			&i.GameTitle,
			&i.GameImage,
			&i.SessionID,
			&i.SessionNotes,
			&i.SessionDuration,
			&i.ListID,
			&i.ListTitle,
			&i.GroupID,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowerCount = `-- name: GetFollowerCount :one
SELECT COUNT(*) FROM follows WHERE following_id = $1
`

func (q *Queries) GetFollowerCount(ctx context.Context, followingID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getFollowerCount, followingID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFollowers = `-- name: GetFollowers :many
SELECT u.id, u.display_name, u.avatar_url, f.created_at AS followed_at
FROM follows f
JOIN users u ON u.id = f.follower_id
WHERE f.following_id = $1
ORDER BY f.created_at DESC
`

type GetFollowersRow struct {
	ID          pgtype.UUID        `json:"id"`
	DisplayName string             `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	FollowedAt  pgtype.Timestamptz `json:"followed_at"`
}

func (q *Queries) GetFollowers(ctx context.Context, followingID pgtype.UUID) ([]GetFollowersRow, error) {
	rows, err := q.db.Query(ctx, getFollowers, followingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFollowersRow{}
	for rows.Next() {
		var i GetFollowersRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.FollowedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowing = `-- name: GetFollowing :many
SELECT u.id, u.display_name, u.avatar_url, f.created_at AS followed_at
FROM follows f
JOIN users u ON u.id = f.following_id
WHERE f.follower_id = $1
ORDER BY f.created_at DESC
`

type GetFollowingRow struct {
	ID          pgtype.UUID        `json:"id"`
	DisplayName string             `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	FollowedAt  pgtype.Timestamptz `json:"followed_at"`
}

func (q *Queries) GetFollowing(ctx context.Context, followerID pgtype.UUID) ([]GetFollowingRow, error) {
	rows, err := q.db.Query(ctx, getFollowing, followerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFollowingRow{}
	for rows.Next() {
		var i GetFollowingRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.FollowedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowingCount = `-- name: GetFollowingCount :one
SELECT COUNT(*) FROM follows WHERE follower_id = $1
`

func (q *Queries) GetFollowingCount(ctx context.Context, followerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getFollowingCount, followerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getGroupMates = `-- name: GetGroupMates :many
SELECT DISTINCT u.id, u.display_name, u.avatar_url
FROM group_members gm1
JOIN group_members gm2 ON gm1.group_id = gm2.group_id AND gm2.user_id != gm1.user_id
JOIN users u ON u.id = gm2.user_id
WHERE gm1.user_id = $1
  AND NOT EXISTS (SELECT 1 FROM follows WHERE follower_id = $1 AND following_id = u.id)
ORDER BY u.display_name
LIMIT 20
`

type GetGroupMatesRow struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName string      `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
}

func (q *Queries) GetGroupMates(ctx context.Context, userID pgtype.UUID) ([]GetGroupMatesRow, error) {
	rows, err := q.db.Query(ctx, getGroupMates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGroupMatesRow{}
	for rows.Next() {
		var i GetGroupMatesRow
		if err := rows.Scan(&i.ID, &i.DisplayName, &i.AvatarUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertActivity = `-- name: InsertActivity :exec
INSERT INTO activity (user_id, type, game_id, session_id, list_id, group_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertActivityParams struct {
	UserID    pgtype.UUID  `json:"user_id"`
	Type      ActivityType `json:"type"`
	GameID    pgtype.UUID  `json:"game_id"`
	SessionID pgtype.UUID  `json:"session_id"`
	ListID    pgtype.UUID  `json:"list_id"`
	GroupID   pgtype.UUID  `json:"group_id"`
}

func (q *Queries) InsertActivity(ctx context.Context, arg InsertActivityParams) error {
	_, err := q.db.Exec(ctx, insertActivity,
		arg.UserID,
		arg.Type,
		arg.GameID,
		arg.SessionID,
		arg.ListID,
		arg.GroupID,
	)
	return err
}

const isFollowing = `-- name: IsFollowing :one
SELECT EXISTS(
    SELECT 1 FROM follows WHERE follower_id = $1 AND following_id = $2
) AS is_following
`

type IsFollowingParams struct {
	FollowerID  pgtype.UUID `json:"follower_id"`
	FollowingID pgtype.UUID `json:"following_id"`
}

func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowing, arg.FollowerID, arg.FollowingID)
	var is_following bool
	err := row.Scan(&is_following)
	return is_following, err
}

const searchUsers = `-- name: SearchUsers :many
SELECT
    u.id,
    u.display_name,
    u.avatar_url,
    EXISTS(
        SELECT 1 FROM follows WHERE follower_id = $1 AND following_id = u.id
    ) AS is_following
FROM users u
WHERE u.display_name ILIKE '%' || $2 || '%'
  AND u.id != $1
ORDER BY u.display_name
LIMIT 20
`

type SearchUsersParams struct {
	Me    pgtype.UUID `json:"me"`
	Query pgtype.Text `json:"query"`
}

type SearchUsersRow struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName string      `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	IsFollowing bool        `json:"is_following"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.Me, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersRow{}
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.IsFollowing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfollowUser = `-- name: UnfollowUser :exec
DELETE FROM follows WHERE follower_id = $1 AND following_id = $2
`

type UnfollowUserParams struct {
	FollowerID  pgtype.UUID `json:"follower_id"`
	FollowingID pgtype.UUID `json:"following_id"`
}

func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) error {
	_, err := q.db.Exec(ctx, unfollowUser, arg.FollowerID, arg.FollowingID)
	return err
}
