// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGoogleUser = `-- name: CreateGoogleUser :one
INSERT INTO users (email, display_name, avatar_url, google_id, password)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, display_name, avatar_url, password, created_at, google_id, bio
`

type CreateGoogleUserParams struct {
	Email       string      `json:"email"`
	DisplayName string      `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	GoogleID    pgtype.Text `json:"google_id"`
	Password    string      `json:"password"`
}

func (q *Queries) CreateGoogleUser(ctx context.Context, arg CreateGoogleUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createGoogleUser,
		arg.Email,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.GoogleID,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Password,
		&i.CreatedAt,
		&i.GoogleID,
		&i.Bio,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (email, display_name, password)
VALUES ($1, $2, $3)
RETURNING id, email, display_name, avatar_url, password, created_at, google_id, bio
`

type CreateUserParams struct {
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
	Password    string `json:"password"`
}

// db/queries/users.sql
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.DisplayName, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Password,
		&i.CreatedAt,
		&i.GoogleID,
		&i.Bio,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, avatar_url, password, created_at, google_id, bio FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Password,
		&i.CreatedAt,
		&i.GoogleID,
		&i.Bio,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, email, display_name, avatar_url, password, created_at, google_id, bio FROM users WHERE google_id = $1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Password,
		&i.CreatedAt,
		&i.GoogleID,
		&i.Bio,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, avatar_url, password, created_at, google_id, bio FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Password,
		&i.CreatedAt,
		&i.GoogleID,
		&i.Bio,
	)
	return i, err
}

const linkGoogleID = `-- name: LinkGoogleID :one
UPDATE users
SET
    google_id  = $1,
    avatar_url = COALESCE($2, avatar_url)
WHERE email = $3
RETURNING id, email, display_name, avatar_url, password, created_at, google_id, bio
`

type LinkGoogleIDParams struct {
	GoogleID  pgtype.Text `json:"google_id"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
	Email     string      `json:"email"`
}

func (q *Queries) LinkGoogleID(ctx context.Context, arg LinkGoogleIDParams) (User, error) {
	row := q.db.QueryRow(ctx, linkGoogleID, arg.GoogleID, arg.AvatarUrl, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Password,
		&i.CreatedAt,
		&i.GoogleID,
		&i.Bio,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
    display_name = COALESCE($2, display_name),
    bio          = COALESCE($3, bio),
    avatar_url   = COALESCE($4, avatar_url)
WHERE id = $1
RETURNING id, email, display_name, avatar_url, password, created_at, google_id, bio
`

type UpdateUserProfileParams struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName string      `json:"display_name"`
	Bio         pgtype.Text `json:"bio"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.DisplayName,
		arg.Bio,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Password,
		&i.CreatedAt,
		&i.GoogleID,
		&i.Bio,
	)
	return i, err
}
